version: "3.1"

services:
  postgres:
    container_name: postgres_strapi_blog
    hostname: postgres_strapi_blog
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: 123456
      POSTGRES_USER: postgres
      POSTGRES_DB: postgres
      PGDATA: /var/lib/postgresql/data/pgdata
    ports:
      - 5432:5432
    volumes:
      - ./postgres-data:/var/lib/postgresql/data/pgdata:rw
